# Generated by Django 3.0.5 on 2020-05-10 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspire', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mission',
            name='file_group',
            field=models.CharField(max_length=36, null=True),
        ),
    ]
