# Generated by Django 3.0.5 on 2020-05-14 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspire', '0002_auto_20200510_1121'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cp_group',
            field=models.CharField(default='fd8f6ce0-c2bb-4dbe-bc72-16a843d1ea7a', max_length=36),
        ),
    ]
