# Generated by Django 3.0.5 on 2020-06-13 05:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inspire', '0004_loginsession'),
    ]

    operations = [
        migrations.AddField(
            model_name='gift',
            name='count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gift',
            name='createdby',
            field=models.ForeignKey(default='dc1c0603-b3e7-4a47-adce-1d08e35f1928', on_delete=django.db.models.deletion.CASCADE, to='inspire.User'),
        ),
        migrations.AddField(
            model_name='gift',
            name='isexchange',
            field=models.BooleanField(default=True),
        ),
    ]
