# Generated by Django 3.0.5 on 2020-06-13 05:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inspire', '0005_auto_20200613_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gift',
            name='count',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='gift',
            name='createdby',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inspire.User'),
        ),
        migrations.AlterField(
            model_name='gift',
            name='isexchange',
            field=models.BooleanField(),
        ),
    ]
